server:
  port: 8090

hibernate:
  allow_update_outside_transaction: true

swagger:
  api-key:
  app-info:
    name: REST API
    description: Test project.
    version: V1
    term-of-service-url: /
    license: License
    license-url: /
    contact:
      name: Yasin Talha AKMAN
      url:
      email: yasin_akman@hotmail.de

spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    job:
      enabled: false


batch:
  updateRatingsJob:
    isEnabled: true
    cronEveryDayAtTenAm: 0 0 10 * * ?
